```{r, echo = FALSE}
opts_chunk$set(echo = FALSE, comment = NA, 
               fig.width = 8, fig.height = 8,
               out.width = 600, out.height = 600)
```

hdnom Report

Generated by hdnom web app

# Nomogram

```{r print_nomogram}
calcedNomogram = calcNomogram()
print(calcedNomogram$'nom')
```

```{r plot_nomogram}
plot(calcedNomogram$'nom')
```

# Model Validation

```{r plot_validate}
calcedValidate = calcValidate()
plot(calcedValidate)
```

```{r summary_validate}
summaryCalcedValidate = format(summary(calcedValidate), digits = 4L)
cbind('-' = rownames(summaryCalcedValidate), summaryCalcedValidate)
```

```{r print_validate}
print(calcedValidate)
```

# Model Calibration

```{r plot_calibrate}
calcedCalibrate = calcCalibrate()
plot(calcedCalibrate,
     xlim = c(input$calibrate_xlim_lo, input$calibrate_xlim_up),
     ylim = c(input$calibrate_xlim_lo, input$calibrate_xlim_up))
```

```{r summary_calibrate}
summaryCalcedCalibrate = format(summary(calcedCalibrate), digits = 4L)
cbind('Group' = rownames(summaryCalcedCalibrate), summaryCalcedCalibrate)
```

```{r print_calibrate}
print(calcedCalibrate)
```

<hr>

Generated by hdnom web app [nomogr.am](http://nomogr.am)

`r Sys.time()`
